import "./globals.css";
import "./responsive-fixes.css";
import { type Metadata } from "next";
import { Roboto } from "next/font/google";
import CursorAndTransitions from "~/components/animations/CursorAndTransitions";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${roboto.variable}`} suppressHydrationWarning>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body style={{ cursor: "none" }} suppressHydrationWarning className="home wp-singular page-template page-template-wavo-elementor-page page-template-wavo-elementor-page-php page page-id-22791 wp-theme-wavo wp-child-theme-wavo-child nt-version-1.0.3 preloader-on split-animation-none use-elementor-style-kit nt-desktop elementor-default elementor-kit-18 elementor-page elementor-page-22791 e--ua-blink e--ua-chrome e--ua-webkit page-loaded cursor-none" data-elementor-device-mode="desktop" data-aos-easing="ease" data-aos-duration="600" data-aos-delay="0">
        <CursorAndTransitions />
        {children}
      </body>
    </html>
  );
}
