const fs = require('fs');

// 1. Start from the raw original HTML
let html = fs.readFileSync('public/home.html', 'utf8');

const bodyMatch = html.match(/<body[^>]*>([\s\S]*)/i);
if (bodyMatch) {
  html = bodyMatch[1];
}

html = html.replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, '');
html = html.replace(/<noscript\b[^<]*(?:(?!<\/noscript>)<[^<]*)*<\/noscript>/gi, '');

// Apply Asset Replacements (these were generated by extract_assets earlier)
// Actually, they were replaced in globals.css, but home.html has some inline images
// Let's replace the main ones if any, or rely on our earlier replace_assets.cjs
// I will just read the current globals.css and apply the same image logic if needed.
// Wait, the user already has the replaced image (the formal pic) in globals.css!
// The HTML only has the cursor and a few other things.
// Wait, did I change the background image to formal pic in HTML?
// No, the hero background was an elementor canvas in globals.css or inline style.
// Oh wait! In home.html, the hero image is in a <canvas> generated by particles.
// The formal pic was actually replaced in globals.css or the canvas?
// Wait, in my previous step, I edited `mask_fix.cjs` and `update_portrait.cjs` which replaced the ACTUAL file in the `assets/` folder!
// So the file `assets/media__1782361166119.png` (or whatever it was) was OVERWRITTEN locally!
// That means the URL in the HTML/CSS doesn't need to change! The file itself was replaced!

// 2. Apply Text Changes
html = html.replace(/Diego/g, 'Hans');
html = html.replace(/Diegovz/g, 'Hans');
html = html.replace(/Based in Madrid, Spain/g, 'cdo, philippines');
html = html.replace(/Designing stuff since <span class=hl-text>2011<\/span>/g, 'Bachelor of Science in <span class=hl-text>Computer Science</span>');

// 3. Apply Cursor Fix
const pinkBoxPath = '<path fill=rgb(194,94,141) fill-opacity=1 d=" M-42,-12 C-42,-12 42,-12 42,-12 C42,-12 42,12 42,12 C42,12 -42,12 -42,12 C-42,12 -42,-12 -42,-12z"></path>';
const replacement = pinkBoxPath + '<text x="-25" y="5" font-family="Helvetica, Arial, sans-serif" font-weight="bold" font-size="15" fill="black">hans</text>';
html = html.replace(pinkBoxPath, replacement);
const svgStart = html.indexOf('url=https://hansvz.com/wp-content/uploads/2025/12/cursor-hansvz-2026-vectors.json><svg');
if (svgStart !== -1) {
    const svgEnd = html.indexOf('</svg>', svgStart) + 6;
    let svgContent = html.substring(svgStart, svgEnd);
    svgContent = svgContent.replace(/<g opacity=1 transform=matrix\([^>]*\)><path fill=rgb\(0,0,0\) fill-opacity=1 d="[^"]*"><\/path><\/g>/g, '');
    html = html.substring(0, svgStart) + svgContent + html.substring(svgEnd);
}

// 4. Rename Sections
html = html.replace(/Some projects<span/g, 'Projects<span');
html = html.replace(/Writing<span/g, 'Skills<span');
html = html.replace(/Fragments of me<span/g, 'About Me<span');
html = html.replace(/Experience<span/g, 'Work Experience<span');

// 4.5 Hero Text Fix
html = html.replace(/<h2 class="elementor-heading-title elementor-size-default">Currently, <span class=hl-text>VP of Design<\/span> at <a class="underline-dvz arrow-contentA hl-text" href=https:\/\/apps\.apple\.com\/co\/app\/rappi-s%C3%BAper-y-comida-online\/id984044296 target=_blank>Rappi<\/a>/g, '<h2 class="elementor-heading-title elementor-size-default"><span class=hl-text>Aspiring Software Engineer</span>');


// 5. Section Reordering and Removing
// A slide starts with <div class="elementor-element... e-con e-child"
// We need a helper to extract a slide
function extractSlide(htmlStr, heading) {
    const headingIndex = htmlStr.indexOf(heading);
    if (headingIndex === -1) return null;
    const parentIdx = htmlStr.lastIndexOf('e-con e-child', headingIndex);
    if (parentIdx === -1) return null;
    const divIdx = htmlStr.lastIndexOf('<div', parentIdx);
    
    // Find next slide
    let nextDivIdx = htmlStr.indexOf('e-con e-child', headingIndex);
    if (nextDivIdx !== -1) {
        nextDivIdx = htmlStr.lastIndexOf('<div', nextDivIdx);
    } else {
        nextDivIdx = htmlStr.indexOf('</div> </div> </div>', headingIndex) + 20;
    }
    return {
        start: divIdx,
        end: nextDivIdx,
        content: htmlStr.substring(divIdx, nextDivIdx)
    };
}

// Get the slides
const eduSlide = extractSlide(html, 'Education<span');
const expSlide = extractSlide(html, 'Work Experience<span');
const readingsSlide = extractSlide(html, 'Readings<span');
const awardsSlide = extractSlide(html, 'Awards &amp; features<span');

// We will keep Edu and Exp. We will DUPLICATE Edu to make Certificates.
let certSlideContent = eduSlide ? eduSlide.content.replace(/Education<span/g, 'Certificates<span') : '';

// Now, we need to carefully replace the ENTIRE block of these 4 slides with our 3 slides!
// The block starts at eduSlide.start and ends at awardsSlide.end (assuming they are in that order).
// Let's verify the order in home.html: Education -> Experience -> Readings -> Awards
if (eduSlide && expSlide && readingsSlide && awardsSlide) {
    // The block we want to replace starts at eduSlide.start and ends at awardsSlide.end
    // Wait, let's just remove them from the string back-to-front so indices don't shift!
    
    // Create the new block: Education, Work Experience, Certificates
    const newBlock = eduSlide.content + expSlide.content + certSlideContent;
    
    // The total block to remove is from eduSlide.start to awardsSlide.end
    html = html.substring(0, eduSlide.start) + newBlock + html.substring(awardsSlide.end);
}

// 6. Fix Canvas Cover to Contain (from earlier fixes)
// I think I didn't change cover to contain in content.ts, I might have done it in globals.css or append_css.
// Just in case, replace any background-size:cover inline styles if they exist.
// There are none in home.html for the main hero.

// Escape backticks and dollars
const escapedHtml = html.replace(/`/g, '\\`').replace(/\$/g, '\\$');
const contentTs = `export const portfolioHtml = \`${escapedHtml}\`;\n`;

fs.writeFileSync('src/app/content.ts', contentTs);
console.log('Rebuild completed successfully!');
